### ISSUE TITLE
Hint: Svelte Preprocess works now

### ISSUE THREAD

**Issue by niklasgrewe** [mattlehrer/sveltekit-vite-tailwind#1]
Hi @mattlehrer 

sveltePreprocess now works with vitejs using the plugin `@svitejs/vite-plugin-svelte`
In my project i am using the following `vite.config.js` 

```js
import { resolve } from 'path';
const svelte = require('@svitejs/vite-plugin-svelte');
const preprocess = require('svelte-preprocess');
const { defineConfig } = require('vite');

module.exports = defineConfig(({ command, mode }) => {
    const isProduction = mode === 'production';
    return {
        plugins: [
            svelte({
                preprocess: preprocess({
                    postcss: true
                }),
                hot: !isProduction,
                emitCss: true
            })
        ],
        resolve: {
            alias: {
                $components: resolve('src/components')
            }
        },
        build: {
            minify: isProduction
        }
    }
})
```
the cool thing is, that directives now works in classes like this:

```html
<style lang="postcss">
   .class {
      @apply sm:text-sm text-base bg-gray-100 hover:bg-gray-200;
   }
</style>
```
feel free to add this to your readme, so other people can use it. of course I can't guarantee if it will work like this with the next updates, but for now it works

**Comment by mattlehrer** [comment]
Thank you. I think svelte-preprocess is working the way it's setup in the repo since Monday. I updated after Vite made some updates.

**Comment by srid** [comment]
> Thank you. I think svelte-preprocess is working the way it's setup in the repo since Monday. I updated after Vite made some updates.

@mattlehrer Could you be specific about what those updates were?

Using tailwind classes in the `<style>` part of my .svelt files errors out:

```
CssSyntaxError: C:/Users/srid/Projects/svdemo/src/routes/$layout.svelte:3:3: The `"bg-red-100"` class does not exist. If `"bg-red-100"` is a custom class, make sure it is defined within a `@layer` directive.
```

I tried to match my svelte.config.cjs close to what you have in master branch, but no luck:

```js
const sveltePreprocess = require('svelte-preprocess');
const node = require('@sveltejs/adapter-node');
const static = require('@sveltejs/adapter-static');
const pkg = require('./package.json');
const { resolve } = require('path');

/** @type {import('@sveltejs/kit').Config} */
module.exports = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: sveltePreprocess({
		postcss: true,
		defaults: {
			style: 'postcss',
		},
	}),
	kit: {
		// By default, `npm run build` will create a standard Node app.
		// You can create optimized builds for different platforms by
		// specifying a different adapter
		adapter: static( { out: "out" }),

		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',

		vite: {
			ssr: {
				noExternal: Object.keys(pkg.dependencies || {})
			},
			resolve: {
				alias: {
					$routes: resolve('src/routes'),
				},
			},
		}
	},
};
```

Repo is here if somebody wants to repro: https://github.com/srid/svdemo

**Comment by mattlehrer** [comment]
Note the double sets of quotes in the error! I didn't see it right away... 

You want this:
```
nav > a {
	@apply bg-red-100;
}
```
i.e., just remove the quotes and it should work. You might have to update your dependencies.

The Vite update was handling empty sourcemaps:
https://github.com/vitejs/vite/commit/103dec9fe80c333e1e8daec53fb08ab597f1120b

**Comment by srid** [comment]
Aha! You're right. Thanks!
